import type { TilesetLayout } from './types'

export const LAYOUT_8X6: TilesetLayout = {
  name: '8x6',
  cols: 8,
  rows: 6,
  tiles: [
    { col: 0, row: 0, peeringIndex: 0 },
    { col: 1, row: 0, peeringIndex: 1 },
    { col: 2, row: 0, peeringIndex: 2 },
    { col: 3, row: 0, peeringIndex: 3 },
    { col: 4, row: 0, peeringIndex: 4 },
    { col: 5, row: 0, peeringIndex: 5 },
    { col: 6, row: 0, peeringIndex: 6 },
    { col: 7, row: 0, peeringIndex: 7 },
    { col: 0, row: 1, peeringIndex: 8 },
    { col: 1, row: 1, peeringIndex: 9 },
    { col: 2, row: 1, peeringIndex: 10 },
    { col: 3, row: 1, peeringIndex: 11 },
    { col: 4, row: 1, peeringIndex: 12 },
    { col: 5, row: 1, peeringIndex: 13 },
    { col: 6, row: 1, peeringIndex: 14 },
    { col: 7, row: 1, peeringIndex: 15 },
    { col: 0, row: 2, peeringIndex: 16 },
    { col: 1, row: 2, peeringIndex: 17 },
    { col: 2, row: 2, peeringIndex: 18 },
    { col: 3, row: 2, peeringIndex: 19 },
    { col: 4, row: 2, peeringIndex: 20 },
    { col: 5, row: 2, peeringIndex: 21 },
    { col: 6, row: 2, peeringIndex: 22 },
    { col: 7, row: 2, peeringIndex: 23 },
    { col: 0, row: 3, peeringIndex: 24 },
    { col: 1, row: 3, peeringIndex: 25 },
    { col: 2, row: 3, peeringIndex: 26 },
    { col: 3, row: 3, peeringIndex: 27 },
    { col: 4, row: 3, peeringIndex: 28 },
    { col: 5, row: 3, peeringIndex: 29 },
    { col: 6, row: 3, peeringIndex: 30 },
    { col: 7, row: 3, peeringIndex: 31 },
    { col: 0, row: 4, peeringIndex: 32 },
    { col: 1, row: 4, peeringIndex: 33 },
    { col: 2, row: 4, peeringIndex: 34 },
    { col: 3, row: 4, peeringIndex: 35 },
    { col: 4, row: 4, peeringIndex: 36 },
    { col: 5, row: 4, peeringIndex: 37 },
    { col: 6, row: 4, peeringIndex: 38 },
    { col: 7, row: 4, peeringIndex: 39 },
    { col: 0, row: 5, peeringIndex: 40 },
    { col: 1, row: 5, peeringIndex: 41 },
    { col: 2, row: 5, peeringIndex: 42 },
    { col: 3, row: 5, peeringIndex: 43 },
    { col: 4, row: 5, peeringIndex: 44 },
    { col: 5, row: 5, peeringIndex: 45 },
    { col: 6, row: 5, peeringIndex: 46 },
  ],
}

export const LAYOUT_11X5: TilesetLayout = {
  name: '11x5',
  cols: 11,
  rows: 5,
  tiles: [
    { col: 0, row: 0, peeringIndex: 8 },
    { col: 1, row: 0, peeringIndex: 12 },
    { col: 2, row: 0, peeringIndex: 4 },
    { col: 3, row: 0, peeringIndex: 2 },
    { col: 4, row: 0, peeringIndex: 7 },
    { col: 5, row: 0, peeringIndex: 11 },
    { col: 6, row: 0, peeringIndex: 10 },
    { col: 7, row: 0, peeringIndex: 3 },
    { col: 8, row: 0, peeringIndex: 9 },
    { col: 9, row: 0, peeringIndex: 38 },
    { col: 0, row: 1, peeringIndex: 30 },
    { col: 1, row: 1, peeringIndex: 46 },
    { col: 2, row: 1, peeringIndex: 20 },
    { col: 3, row: 1, peeringIndex: 16 },
    { col: 4, row: 1, peeringIndex: 28 },
    { col: 5, row: 1, peeringIndex: 29 },
    { col: 6, row: 1, peeringIndex: 27 },
    { col: 7, row: 1, peeringIndex: 18 },
    { col: 8, row: 1, peeringIndex: 19 },
    { col: 9, row: 1, peeringIndex: 17 },
    { col: 0, row: 2, peeringIndex: 22 },
    { col: 1, row: 2, peeringIndex: 26 },
    { col: 2, row: 2, peeringIndex: 15 },
    { col: 3, row: 2, peeringIndex: 13 },
    { col: 4, row: 2, peeringIndex: 21 },
    { col: 5, row: 2, peeringIndex: 25 },
    { col: 6, row: 2, peeringIndex: 24 },
    { col: 7, row: 2, peeringIndex: 14 },
    { col: 8, row: 2, peeringIndex: 23 },
    { col: 9, row: 2, peeringIndex: 45 },
    { col: 10, row: 2, peeringIndex: 42 },
    { col: 0, row: 3, peeringIndex: 5 },
    { col: 1, row: 3, peeringIndex: 6 },
    { col: 2, row: 3, peeringIndex: 1 },
    { col: 3, row: 3, peeringIndex: 0 },
    { col: 4, row: 3, peeringIndex: 31 },
    { col: 5, row: 3, peeringIndex: 40 },
    { col: 6, row: 3, peeringIndex: 41 },
    { col: 7, row: 3, peeringIndex: 39 },
    { col: 8, row: 3, peeringIndex: 44 },
    { col: 9, row: 3, peeringIndex: 43 },
    { col: 10, row: 3, peeringIndex: 32 },
    { col: 4, row: 4, peeringIndex: 34 },
    { col: 5, row: 4, peeringIndex: 33 },
    { col: 6, row: 4, peeringIndex: 37 },
    { col: 7, row: 4, peeringIndex: 35 },
    { col: 8, row: 4, peeringIndex: 36 },
  ],
}

export function getLayout(name: string): TilesetLayout {
  return name === '8x6' ? LAYOUT_8X6 : LAYOUT_11X5
}
